config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  # match '/contacts', to: 'contacts#new', via: :get
  # match '/contacts', to: 'contacts#create', via: :post

  match '/contacts', to: 'static_pages#create_contact', via: :post

  match '/home', to: 'static_pages#home', via: :get
  match '/about', to: 'static_pages#about', via: :get
  match '/contact', to: 'static_pages#contact', via: :get
  match '/portfolio', to: 'static_pages#portfolio', via: :get

  #match ':controller(/:action(/:id))', via: :get
  #match ':controller(/:action(/:id(.:format)))', via: :get

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    @contact
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params_with_no_date)
  end

  private
  def contact_params_with_no_date
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def about
  end

  def portfolio
  end

  def contact
    @contact = Contact.new
  end

  def create_contact
    @contact = Contact.new(contact_params_with_no_date)
    if (@contact.save!)
      flash[:success] = 'Thanks for your contact. You will get in touch soon.'
    else
      flash[:danger] = 'Ooops!'
    end

    redirect_to contact_path
  end

  private
  def contact_params_with_no_date
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def contact
    @contact = Contact.new
  end
end

app/views/contacts/create.html.erb
<div id="main">
  <h1>Contacts#create</h1>
  <p>Find me in app/views/contacts/create.html.erb</p>
</div>

app/views/contacts/new.html.erb
<div id="main">
  <h2>Get In Touch</h2>
  <p>Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem
    semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor.</p>
  <div class="row">
    <div class="8u 12u$(small)">
      <%= form_for(@contact) do |c| %>
          <%= c.label :name %>
          <%= c.text_field :name %>

          <%= c.label :email %>
          <%= c.email_field :email %>

          <%= c.label :message %>
          <%= c.text_field :message %>

          <ul class="actions">
            <%= c.submit 'Send Message' %>
          </ul>
      <% end %>
    </div>
    <div class="4u$ 12u$(small)">
      <ul class="labeled-icons">
        <li>
          <h3 class="icon fa-home"><span class="label">Address</span></h3>
          1 Ramsay Street<br/>
          Collaroy, NSW 2036<br/>
          Australia
        </li>
        <li>
          <h3 class="icon fa-mobile"><span class="label">Phone</span></h3>
          0478 510 593
        </li>
        <li>
          <h3 class="icon fa-envelope-o"><span class="label">Email</span></h3>
          <a href="#">igorrmotta@gmail.com</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div id="main">
  <h1>Contacts#show</h1>
  <p>Find me in app/views/contacts/show.html.erb</p>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <ul class="icons">
    <li>
      <%= link_to '#', class: 'icon fa-twitter' do %>
          <span class="label">Twitter</span>
      <% end %>
    </li>
    <li>
      <%= link_to '#', class: 'icon fa-github' do %>
          <span class="label">GitHub</span>
      <% end %>
    </li>
    <li>
      <%= link_to '#', class: 'icon fa-dribble' do %>
          <span class="label">Dribble</span>
      <% end %>
    </li>
    <li>
      <%= link_to '#', class: 'icon fa-envelope-o' do %>
          <span class="label">Email</span>
      <% end %>
    </li>
  </ul>
  <ul class="copyright">
    <li>&copy; igorrmotta</li>
    <li>Design: <%= link_to 'HTML5 UP', 'http://html5up.net' %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <nav id="menu">
    <ul>
      <li><%= link_to 'Home', home_path, class: (current_page?(action: 'home') ? 'selected' : '') %> </li>
      <li><%= link_to 'About', about_path, class: (current_page?(action: 'about') ? 'selected' : '') %> </li>
      <li><%= link_to 'Contact', contact_path, class: (current_page?(action: 'contact') ? 'selected' : '') %></li>
      <li><%= link_to 'Portfolio', portfolio_path, class: (current_page?(action: 'portfolio') ? 'selected' : '') %> </li>
    </ul>
  </nav>

  <%= link_to image_tag('fulls/avatar.jpg', alt: 'avatar'), root_path, class: 'image avatar' %>
  <h1><strong>Igor Rodrigues Motta</strong></h1>
  <h5>Web/Mobile Developer </h5>

  a <strong>Software Developer</strong> who comes to make difference.<br/>
  I like to call myself as a <strong>Design Thinker</strong>. A person who turns <i><u>problems</u></i> into
  <i><u>solutions</u></i>.
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IgorrmottaWebsite</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--[if lte IE 8]>  <%= stylesheet_link_tag 'ie8.scss', media: 'all', 'data-turbolinks-track' => true %><![endif]-->

  <%= javascript_include_tag 'jquery.js', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'skel.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.poptrox.min', 'data-turbolinks-track' => true %>
  <!--[if lte IE 8]><%= javascript_include_tag 'ie/respond.min.js', 'data-turbolinks-track' => true %><![endif]-->
  <!--[if lte IE 8]><%= javascript_include_tag 'ie/html5shiv.js', 'data-turbolinks-track' => true %><![endif]-->

  <%= csrf_meta_tags %>
</head>
<body id="top">
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/_contact_form.html.erb
<h2>Get In Touch</h2>
<p>Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem
  semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor.</p>
<div class="row">
  <div id="message">
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </div>
  <div class="8u 12u$(small)">
    <%= form_for(@contact) do |c| %>
        <%= c.label :name %>
        <%= c.text_field :name %>

        <%= c.label :email %>
        <%= c.email_field :email %>

        <%= c.label :message %>
        <%= c.text_field :message %>

        <ul class="actions">
          <%= c.submit 'Send Message' %>
        </ul>
    <% end %>
  </div>
  <div class="4u$ 12u$(small)">
    <ul class="labeled-icons">
      <li>
        <h3 class="icon fa-home"><span class="label">Address</span></h3>
        1 Ramsay Street<br/>
        Collaroy, NSW 2036<br/>
        Australia
      </li>
      <li>
        <h3 class="icon fa-mobile"><span class="label">Phone</span></h3>
        0478 510 593
      </li>
      <li>
        <h3 class="icon fa-envelope-o"><span class="label">Email</span></h3>
        <a href="#">igorrmotta@gmail.com</a>
      </li>
    </ul>
  </div>
</div>

app/views/static_pages/about.html.erb
<div id="main">
  <section id="one">
    <header class="major">
      <h2>Ipsum lorem dolor aliquam ante commodo<br/>
        magna sed accumsan arcu neque.</h2>
    </header>
    <p>Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in
      adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit
      enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem
      neque cubilia.</p>
    <ul class="actions">
      <li><%= link_to 'More', '/static_pages/about', class: 'button' %> </li>
    </ul>
  </section>
</div>

app/views/static_pages/contact.html.erb
<div id="main">
  <%= render 'static_pages/contact_form' %>
</div>

app/views/static_pages/home.html.erb
<div id="main">
  <section id="one">
    <header class="major">
      <h2>Hi - I'm Igor. I've been building software since 2010. Researching, Coding, Reviewing, Testing and
        Designing.</h2>
    </header>
    <p>Studied 'Information Technology', and studying 'Digital Design' focused in the creative side.</p>
    <blockquote>
      "Logic will get you from A to B. Imagination will take you everywhere."
      Albert Einstein
    </blockquote>
    Consider me as an enthusiast of web and mobile technologies. I've been studying many different platforms about
    those past 2 years.
    </p>
    <ul class="actions">
      <li><%= link_to 'More', '/static_pages/about', class: 'button' %> </li>
    </ul>
  </section>
  <section id="two">
    <h2>Recent Work</h2>
    <div class="row">
      <article class="6u 12u$(xsmall) work-item">
        <%= link_to image_tag('thumbs/01.jpg'), class: 'image fit thumb' %>
        <h3>Magna sed consequat tempus</h3>
        <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>
      </article>
      <article class="6u$ 12u$(xsmall) work-item">
        <%= link_to image_tag('thumbs/02.jpg'), class: 'image fit thumb' %>
        <h3>Ultricies lacinia interdum</h3>
        <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>
      </article>
      <ul class="actions">
        <li><%= link_to 'Full Portfolio', '/portfolio', class: 'button' %></li>
      </ul>
    </div>
  </section>
  <section id="three">
    <%= render 'static_pages/contact_form' %>
  </section>
</div>

app/views/static_pages/portfolio.html.erb
<div id="main">
  <article class="6u 12u$(xsmall) work-item">
    <%= link_to image_tag('thumbs/01.jpg'), class: 'image fit thumb' %>
    <h3>Magna sed consequat tempus</h3>
    <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>
  </article>
  <article class="6u$ 12u$(xsmall) work-item">
    <%= link_to image_tag('thumbs/02.jpg'), class: 'image fit thumb' %>
    <h3>Ultricies lacinia interdum</h3>
    <p>Lorem ipsum dolor sit amet nisl sed nullam feugiat.</p>
  </article>
</div>